### ISSUE TITLE
Container does not stop

### ISSUE THREAD

**Issue by kroese** [ubergeek77/lemmy-docker-multiarch#2]
I'm not sure if this is caused by this specific docker build, or a general problem in lemmy-ui, but I noticed that from 0.18.4 the lemmy-ui container does not stop gracefully anymore. It is killed by Docker after the timeout (default 10 seconds) instead of shutting down cleanly.

**Comment by ubergeek77** [comment]
My apologies, but there is nothing I can do about this. That non-graceful exit behavior you describe is pretty typical of Node apps. My Dockerfile is functionally identical to the official one, with only minor build changes to get it building across multiple architectures. In fact, the Dockerfile in this repo for Lemmy-UI hasn't actually changed in nearly 2 months.

Please try reproducing this with the official Lemmy UI image, and if you are able to reproduce it, file an issue on LemmyNet/lemmy-ui.
