### ISSUE TITLE
Is Alpine Edge still needed?

### ISSUE THREAD

**Issue by kroese** [ubergeek77/lemmy-docker-multiarch#3]
In the frontend Dockerfile it uses alpine-edge to solve some issues with sharp/libvips.

As I submitted this Dockerfile as a pullrequest (https://github.com/LemmyNet/lemmy-ui/pull/2235) I was wondering if edge is still needed?

Because I dont know exactly what issues you had, but those may be fixed in the normal alpine by now (since it was more than a month ago that you created this Dockerfile)?

**Comment by ubergeek77** [comment]
I'll take a look after the holiday week, thanks

**Comment by ubergeek77** [comment]
I did forget, but I've also been quite busy :)

However, as of at least 0.19, ARM is officially supported by Lemmy, so this repository has served its purpose and is no longer needed.

I'm going to pause builds, and if Lemmy ever messes up their ARM images again, I'll consider maintaining these images again.

**Comment by ubergeek77** [comment]
Actually, are you on 32-bit ARM? I didn't realize Lemmy still isn't building for that -_-

**Comment by ubergeek77** [comment]
Since Lemmy still doesn't provide images for ARM32, I'll go ahead and update this build stack after I get Lemmy Easy Deploy patched up

**Comment by ubergeek77** [comment]
Ah, I didn't realize that got upstreamed! Neat!

It was a hack, but I added it because there was some weirdness with the version of `sharp` Lemmy was using. It's been a while, but if I remember correctly, there was a bug/regression/incompatibility between sharp <--> libvips, and getting a newer version of libvips was the only option at the time.

I'll run a test build without it and see if it's still needed.

**Comment by ubergeek77** [comment]
I did start investigating this, but the build failed, and I won't be able to properly get a build going until after the new year. You can see my current branch and see the build if you like, though:

https://github.com/ubergeek77/lemmy-docker-multiarch/actions/runs/7243235864

My current images are working, so I'm not in *too* much of a hurry to sort this out, but if Lemmy doesn't move too fast I'll probably have it figured out before 0.19.1

Still surprised they accepted a fix like this, but if it's upstream, it's upstream 😅

**Comment by ubergeek77** [comment]
@kroese I'm back investigating this with Lemmy 0.19.2

When trying to build for `linux/arm/v7` it fails with:

```
 > [builder 15/19] RUN NODE_OPTIONS="--max-old-space-size=8192" yarn build:prod:
0.298
0.298 <--- Last few GCs --->
0.298
0.298 [1:0xf51860a0]       17 ms: Mark-Compact (reduce) 0.6 (1.6) -> 0.6 (1.6) MB, 2.38 / 0.00 ms  (average mu = 0.079, current mu = 0.098) last resort; GC in old space requested
0.298 [1:0xf51860a0]       20 ms: Mark-Compact (reduce) 0.6 (1.6) -> 0.6 (1.6) MB, 3.44 / 0.00 ms  (average mu = 0.036, current mu = 0.003) last resort; GC in old space requested
0.298
0.298
0.298 <--- JS stacktrace --->
0.298
0.298
0.298 #
0.298 # Fatal javascript OOM in CALL_AND_RETRY_LAST
0.298 #
0.298
```

For some reason, ***only*** a `linux/arm/v7` build is showing this error. Building for `linux/arm64` builds fine on the exact same ARM host. I have no idea why this could be.

The machine has plenty of memory, and a swap file that isn't being heavily utilized, so I think this error is misleading. It might have something to do with some dependency needing a certain page file size or other memory shenanigans.

Are you able to build Lemmy-UI for `linux/arm/v7`? I see you were the one that requested a 32-bit ARM build for Lemmy-UI originally.

**Comment by ubergeek77** [comment]
Nevermind. It looks like `NODE_OPTIONS="--max-old-space-size=8192"` is way too high for my builder and also doesn't seem necessary.

I'll get my lemmy-ui images working and then PR the improvements back to upstream.

**Comment by ubergeek77** [comment]
At least as of 0.19.2, basically no changes are needed for `lemmy-ui` to build for any target, you shouldn't need to cross compile. The same Dockerfile should build on `amd64`, `arm64`, and `arm/v7`. The upstream image doesn't do cross compilation or node-prune shenanigans anymore. After my build succeeds and I push this to `main`, you can try that image and see if it works for you.

The backend `lemmy` image is a different story. They seem to have some complex steps but I don't really understand the rationale for; they have a separate builder and runner image just for `arm64`, when the original `rust` image ships for both platforms.

I'll bring this up to them when I submit this PR. I'd like to be the one to get on the contributor's list this time :p

**Comment by ubergeek77** [comment]
Hmmmm. I could understand the different FROM steps, but I'm still not sure why a separate image is needed for ARM64. The images I just built for 0.19.2 work on all platforms with a single `FROM` step for the builder.

I don't think I'll rock that boat though. It's still ***much*** better than it used to be.

As for this particular issue, the answer to "Is Alpine Edge still needed" is: no! Looks like it isn't!

**Comment by ubergeek77** [comment]
Ah, I see. That does make sense.
